FORM GET .
SELECT A~ORDER_ID A~CUST_ID B~CITY A~MAT_ID C~MAT_NAME A~QUANTITY C~PRICE
FROM ZSALES_ORDER AS A
INNER JOIN ZCUSTOMER1 AS B
ON A~CUST_ID = B~CUST_ID
INNER JOIN ZPRODUCT1 AS C
ON A~MAT_ID = C~MAT_ID
INTO TABLE IT1
WHERE A~ORDER_ID IN OID AND A~CUST_ID IN CID.

LOOP AT IT1 INTO WA1.
WA1-TOTAL_AMOUNT =  WA1-PRICE * WA1-QUANTITY.
MODIFY IT1 FROM WA1.
ENDLOOP.
ENDFORM.


FORM FIELDCATEGLOG .

* Order ID
  CLEAR WA_FIELDCAT.
  WA_FIELDCAT-COL_POS   = 1.
  WA_FIELDCAT-FIELDNAME = 'ORDER_ID'.
  WA_FIELDCAT-TABNAME   = 'IT1'.
  WA_FIELDCAT-SELTEXT_M = 'Order ID'.
  WA_FIELDCAT-OUTPUTLEN = 10.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.

* Customer ID
  CLEAR WA_FIELDCAT.
  WA_FIELDCAT-COL_POS   = 2.
  WA_FIELDCAT-FIELDNAME = 'CUST_ID'.
  WA_FIELDCAT-TABNAME   = 'IT1'.
  WA_FIELDCAT-SELTEXT_M = 'Customer ID'.
  WA_FIELDCAT-OUTPUTLEN = 10.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.

* City
  CLEAR WA_FIELDCAT.
  WA_FIELDCAT-COL_POS   = 3.
  WA_FIELDCAT-FIELDNAME = 'CITY'.
  WA_FIELDCAT-TABNAME   = 'IT1'.
  WA_FIELDCAT-SELTEXT_M = 'City'.
  WA_FIELDCAT-OUTPUTLEN = 15.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.

* Material ID
  CLEAR WA_FIELDCAT.
  WA_FIELDCAT-COL_POS   = 4.
  WA_FIELDCAT-FIELDNAME = 'MAT_ID'.
  WA_FIELDCAT-TABNAME   = 'IT1'.
  WA_FIELDCAT-SELTEXT_M = 'Material ID'.
  WA_FIELDCAT-OUTPUTLEN = 10.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.

* Material Name
  CLEAR WA_FIELDCAT.
  WA_FIELDCAT-COL_POS   = 5.
  WA_FIELDCAT-FIELDNAME = 'MAT_NAME'.
  WA_FIELDCAT-TABNAME   = 'IT1'.
  WA_FIELDCAT-SELTEXT_M = 'Material Name'.
  WA_FIELDCAT-OUTPUTLEN = 20.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.

* Quantity
  CLEAR WA_FIELDCAT.
  WA_FIELDCAT-COL_POS   = 6.
  WA_FIELDCAT-FIELDNAME = 'QUANTITY'.
  WA_FIELDCAT-TABNAME   = 'IT1'.
  WA_FIELDCAT-SELTEXT_M = 'Quantity'.
  WA_FIELDCAT-OUTPUTLEN = 10.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.

* Price
  CLEAR WA_FIELDCAT.
  WA_FIELDCAT-COL_POS   = 7.
  WA_FIELDCAT-FIELDNAME = 'PRICE'.
  WA_FIELDCAT-TABNAME   = 'IT1'.
  WA_FIELDCAT-SELTEXT_M = 'Price'.
  WA_FIELDCAT-OUTPUTLEN = 12.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.

* Total Amount
  CLEAR WA_FIELDCAT.
  WA_FIELDCAT-COL_POS   = 8.
  WA_FIELDCAT-FIELDNAME = 'TOTAL_AMOUNT'.
  WA_FIELDCAT-TABNAME   = 'IT1'.
  WA_FIELDCAT-SELTEXT_M = 'Total Amount'.
  WA_FIELDCAT-OUTPUTLEN = 15.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
ENDFORM.

FORM LAYOUT .
* LAYOUT PREDEFINE FIELD IS ZEBRA
*SET COLOUM WIDTH ACCORDING TO DATA
  WA_LAYOUT-ZEBRA = 'X'.
  WA_LAYOUT-COLWIDTH_OPTIMIZE = 'X'.
ENDFORM.

FORM SORT .
*SORT POSITION , WHICH COLOUMN WANT TO SORT, UP = 'ASCENDING ORDER'
  CLEAR WA_SORT.
  WA_SORT-SPOS = 1.
  WA_SORT-FIELDNAME = 'ORDER_ID'.
  WA_SORT-UP = 'X'.
  APPEND WA_SORT TO IT_SORT.
ENDFORM.

FORM DISPLAY .

 CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
EXPORTING

  I_CALLBACK_PROGRAM                = SY-CPROG
  IT_EVENTS                         = ITE
  IS_LAYOUT                         = WA_LAYOUT
  IT_FIELDCAT                       = IT_FIELDCAT
  IT_SORT                           = IT_SORT

   TABLES
     T_OUTTAB                          = IT1.


ENDFORM.

FORM EVENT .
CLEAR WAE.
WAE-NAME = 'USER COMMAND'.
WAE-FORM = 'CLASSICAL'.
APPEND WAE TO ITE.

CLEAR WAE.
WAE-NAME = 'TOP_OF_PAGE'.
WAE-FORM = 'HEADING'.
APPEND WAE TO ITE.
ENDFORM.

FORM HEADING.

DATA: STR TYPE STRING.
DATA: WAL TYPE SLIS_LISTHEADER,
      ITL TYPE SLIS_T_LISTHEADER.

CLEAR WAL.
WAL-TYP = 'H'.
WAL-INFO = 'SALES ORDER REPORT'.
APPEND WAL TO ITL.
CLEAR WAL.
WAL-TYP = 'H'.
WAL-INFO = 'USERNAME'.
WAL-INFO = SY-UNAME.
APPEND WAL TO ITL.
CLEAR WAL.
WAL-TYP = 'S'.
WAL-KEY = 'DATE'.
CONCATENATE SY-DATUM+6(2) SY-DATUM+4(2) SY-DATUM+0(4) INTO STR SEPARATED BY '.'.
WAL-INFO = STR.
APPEND WAL TO ITL.

CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
  EXPORTING
    IT_LIST_COMMENTARY       = ITL.
          .
ENDFORM.
