TABLES: ZCUSTOMER1, ZPRODUCT1, ZSALES_ORDER.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-000.
SELECT-OPTIONS: NID FOR ZSALES_ORDER-ORDER_ID.
SELECTION-SCREEN : END OF  BLOCK B1.

TYPES: BEGIN OF TY_STR1,
       ORDER_ID TYPE ZORDER_ID1,
       CUST_NAME TYPE ZCUST_NAME1,
       CITY TYPE ZCITY11,
       MAT_NAME TYPE ZMAT_NAME,
       QUANTITY TYPE ZQUANTITY11,
       PRICE TYPE ZPRICE111,
       TOTAL_AMOUNT TYPE ZPRODUCT1-PRICE,
       END OF TY_STR1,

       BEGIN OF TY_STR2,
       CUST_ID TYPE ZCUST_ID1 ,
       CUST_NAME TYPE ZCUST_NAME1 ,
       CITY TYPE ZCITY11,
       PHONE TYPE ZPHONE11,
       MAT_ID TYPE ZMAT_ID,
       MAT_NAME TYPE ZMAT_NAME,
       CATEGORY TYPE ZCATEGORY,
       PRICE TYPE ZPRICE111,
       ORDER_ID TYPE ZORDER_ID1,
       ORDER_DATE TYPE ZORDER_DATE1,
       QUANTITY TYPE ZQUANTITY11,
       END OF TY_STR2.

 DATA: IT1 TYPE TABLE OF TY_STR1,
       WA1 TYPE TY_STR1,
       IT2 TYPE TY_STR2,
       WA2 TYPE  TY_STR2.
