FORM GET .
SELECT ORDER_ID CUST_NAME CITY MAT_NAME QUANTITY PRICE
FROM ZSALES_ORDER
INNER JOIN ZCUSTOMER1
ON ZSALES_ORDER~CUST_ID = ZCUSTOMER1~CUST_ID
INNER JOIN ZPRODUCT1
ON ZSALES_ORDER~MAT_ID = ZPRODUCT1~MAT_ID
INTO TABLE IT1
WHERE ORDER_ID IN NID.
ENDFORM.

FORM DISPLAY .

WRITE:/ 'ORDER_ID' COLOR 4,
      15 'CUST_NAME' COLOR 4,
      35  'CITY' COLOR 4,
      50  'MAT_NAME' COLOR 4,
      70  'QUANTITY' COLOR 4,
      85  'PRICE' COLOR 4,
      100 'TOTAL_AMOUNT' COLOR 4.
LOOP AT IT1 INTO WA1.
WA1-TOTAL_AMOUNT = WA1-QUANTITY * WA1-PRICE.
WRITE:/ WA1-ORDER_ID HOTSPOT,
      15 WA1-CUST_NAME,
      35  WA1-CITY,
      50  WA1-MAT_NAME,
      70  WA1-QUANTITY,
      85  WA1-PRICE,
      100 WA1-TOTAL_AMOUNT.

HIDE WA1-ORDER_ID.
ENDLOOP.
ENDFORM.
AT LINE-SELECTION.
SELECT SINGLE
ZCUSTOMER1~CUST_ID CUST_NAME PHONE CITY
ZPRODUCT1~MAT_ID MAT_NAME CATEGORY PRICE
ORDER_ID ORDER_DATE QUANTITY
FROM ZSALES_ORDER
INNER JOIN ZCUSTOMER1
ON ZSALES_ORDER~CUST_ID = ZCUSTOMER1~CUST_ID
INNER JOIN ZPRODUCT1
ON ZSALES_ORDER~MAT_ID = ZPRODUCT1~MAT_ID
INTO CORRESPONDING FIELDS OF WA2
WHERE ZSALES_ORDER~ORDER_ID = WA1-ORDER_ID.

WRITE:/ 'CUSTOMER DETAILS',
 '---------------------------------------------------------------------'.
WRITE:/ 'Customer ID :', WA2-CUST_ID,
      / 'Customer Name :', WA2-CUST_NAME,
      / 'City :', WA2-CITY.
ULINE.
WRITE: / 'PRODUCT DETAILS',
        '---------------------------------------------------------------------'.

WRITE: / 'Material ID :', WA2-MAT_ID,
       / 'Material Name :', WA2-MAT_NAME,
       /'Category :', WA2-CATEGORY,
       /'Price :', WA2-PRICE.
ULINE.
WRITE: / 'ORDER DETAILS',
 '---------------------------------------------------------------------'.
WRITE: / 'Order ID :', WA2-ORDER_ID,
      / 'Order Date :', WA2-ORDER_DATE,
      / 'Quantity :', WA2-QUANTITY.
ULINE.
