FORM INIT .
NID-SIGN = 'I'.
NID-OPTION = 'BT'.
NID-LOW = 101. 
NID-HIGH = 106.
APPEND NID.
ENDFORM.

FORM GET .
IF NID-LOW < 101 OR NID-HIGH > 106.
MESSAGE 'ENTER VALID INPUT' TYPE 'E'.
ENDIF.
ENDFORM.

FORM GET1 .

SELECT
      ZSALES_ORDER~ORDER_ID
      ZCUSTOMER1~CUST_NAME
      ZCUSTOMER1~CITY
      ZPRODUCT1~MAT_NAME
      ZSALES_ORDER~QUANTITY
      ZPRODUCT1~PRICE
      ZSALES_ORDER~ORDER_DATE
FROM ZSALES_ORDER
INNER JOIN ZCUSTOMER1
ON ZSALES_ORDER~CUST_ID = ZCUSTOMER1~CUST_ID
INNER JOIN ZPRODUCT1
ON ZSALES_ORDER~MAT_ID = ZPRODUCT1~MAT_ID
INTO TABLE IT1
WHERE ZSALES_ORDER~ORDER_ID IN NID.
ENDFORM.

FORM DISPLAY .
WRITE: /
'ORDER_ID' COLOR 3,
15 'CUST_NAME' COLOR 3,
35 'CITY' COLOR 3,
50 'MAT_NAME' COLOR 3,
70 'QUANTITY' COLOR 3,
85 'PRICE' COLOR 3,
100 'ORDER_DATE' COLOR 3.

ULINE.

LOOP AT IT1 INTO WA1.

WRITE: /  WA1-ORDER_ID,
      15 WA1-CUST_NAME ,
      35 WA1-CITY,
      50 WA1-MATNAME,
      70 WA1-QUANTITY,
      85 WA1-PRICE,
      100 WA1-ORDER_DATE.
ENDLOOP.

ENDFORM.
