TABLES: ZCUSTOMER1, ZPRODUCT1, ZSALES_ORDER.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-000.
SELECT-OPTIONS: NID FOR ZSALES_ORDER-ORDER_ID.
SELECTION-SCREEN: END OF BLOCK B1.


TYPES:
BEGIN OF TY_STR,
ORDER_ID TYPE ZORDER_ID1,
CUST_NAME TYPE ZCUST_NAME1,
CITY TYPE ZCITY11,
MATNAME TYPE ZMAT_NAME,
QUANTITY TYPE ZQUANTITY11,
PRICE TYPE ZPRICE111 ,
ORDER_DATE TYPE ZORDER_DATE1,
END OF TY_STR.

DATA:
      IT1 TYPE TABLE OF TY_STR,
      WA1 TYPE TY_STR.
