TABLES: ZCUSTOMER1, ZPRODUCT1, ZSALES_ORDER.

TYPE-POOLS : SLIS.

SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
  SELECT-OPTIONS: OID FOR ZSALES_ORDER-ORDER_ID,
                  CID FOR ZSALES_ORDER-CUST_ID.
  PARAMETERS:
  H_VALUE AS CHECKBOX.
SELECTION-SCREEN: END OF BLOCK B1.

TYPES:
BEGIN OF TY_STR1,
ORDER_ID TYPE ZORDER_ID1 ,
CUST_ID TYPE ZCUST_ID1 ,
CITY TYPE ZCITY11 ,
MAT_ID TYPE ZMAT_ID,
MAT_NAME TYPE ZMAT_NAME,
QUANTITY TYPE ZQUANTITY11,
PRICE TYPE ZPRICE111,
TOTAL_AMOUNT TYPE ZPRODUCT1-PRICE,
END OF TY_STR1.

DATA:
      IT1 TYPE TABLE OF TY_STR1,
      WA1 TYPE          TY_STR1,

*FIELD CATALOG
      IT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,
      WA_FIELDCAT TYPE SLIS_FIELDCAT_ALV,

*EVENTS
       ITE TYPE SLIS_T_EVENT,
       WAE TYPE SLIS_ALV_EVENT,

*LAYOUT
      WA_LAYOUT TYPE SLIS_LAYOUT_ALV,

*SORT
       IT_SORT TYPE SLIS_T_SORTINFO_ALV,
       WA_SORT TYPE SLIS_SORTINFO_ALV.
